@startuml
enum Attribute {
Speed
Size
Color
}

enum Need {
Sleep
Hunger
ReproductiveUrge
Thirst
}

enum Distance {
ToWater
ToFood
}

enum Species {
Chicken
Fox
Grass
}

enum Inorganic {
Water
}

enum State {
LookForFood
LookForWater
Stealth
Sleep
Wander
Reproduce
AsexualReproduce
Idle
}

class StateExtensions {
+{static} void SolveState(State state, IAgentController controller)
}

note right of StateExtensions
Es static
end note
@enduml